### ISSUE TITLE
Can't run grunt-throttle

### ISSUE THREAD

**Issue by eitanp461** [tjgq/grunt-throttle#1]
I setup the simplest environment for running grunt-throttle.
My package.json includes only grunt-throttle.
My Gruntfile includes only grunt-throttle configuration,

I am getting this error in command line:

  Initializing
  Command-line options: --verbose

  Reading "Gruntfile.js" Gruntfile...OK

  Registering Gruntfile tasks.

  Registering "grunt-throttle" local Npm module tasks.
  Reading c:\temp\node_modules\grunt-throttle\package.json...OK
  Parsing c:\temp\node_modules\grunt-throttle\package.json...OK
  Loading "throttle.js" tasks...ERROR

> > TypeError: Cannot read property 'prototype' of undefined
> >     at exports.inherits (util.js:538:43)
> >     at Object.<anonymous> (c:\temp\node_modules\grunt-throttle\node_modules\stream-throttle\src\throttle.js:19:1)
> >     at Module._compile (module.js:449:26)
> >     at Object.Module._extensions..js (module.js:467:10)
> >     at Module.load (module.js:356:32)
> >     at Function.Module._load (module.js:312:12)
> >     at Module.require (module.js:362:17)
> >     at require (module.js:378:17)
> >     at Object.<anonymous> (c:\temp\node_modules\grunt-throttle\node_modules\stream-throttle\index.js:1:80)
> >     at Module._compile (module.js:449:26)
> >   Initializing config...OK
> >   Loading "Gruntfile.js" tasks...OK
> > - default

  No tasks specified, running default tasks.
  Running tasks: default

  Running "default" task
  Warning: Task "throttle" not found. Use --force to continue.

  Aborted due to warnings.

This is my grunt version:
  c:\temp>grunt --version
  grunt-cli v0.1.9
  grunt v0.4.1

OS:
Windows 7 Enterprise
Service Pack 1

Thanks for your help,
Eitan

**Comment by tjgq** [comment]
Can you tell me which Node version you're using?

**Comment by eitanp461** [comment]
c:>node --version
v0.8.23

**Comment by tjgq** [comment]
That explains it: grunt-throttle depends on stream-throttle, which in turn depends on the Stream.Transform API, which was only introduced in Node v0.10.

So unfortunately you cannot run grunt-throttle unless you upgrade to Node 0.10.

I will be upgrading the package.json file later to specify that Node >= 0.10 is required.

Thanks!

**Comment by eitanp461** [comment]
Thanks for the answer. Now I have a good reason to upgrade Node :)
