### ISSUE TITLE
How's this supposed to work?

### ISSUE THREAD

**Issue by roman01la** [tjgq/grunt-throttle#2]
I just don't get it, I've a task specified, it runs for 10ms and that's all. Any guidelines please?

**Comment by tjgq** [comment]
Hi,

Grunt-throttle will not prevent Grunt from exiting. It is intended to be used (in all fairness: I intended to use it myself) in conjuction with grunt-watch. Here's a minimal Gruntfile.js that will work:

```
module.exports = function(grunt) {

  grunt.initConfig({

    watch: {},

    connect: {
      server: {
        options: {
          port: 9000,
          base: '.',
        }
      }
    },

    throttle: {
      default: {
          remote_host: 'localhost',
          remote_port: 9000,
          local_port: 9001,
          upstream: 10*1024,
          downstream: 100*1024
      }
    }

  });

  grunt.loadNpmTasks('grunt-contrib-watch');
  grunt.loadNpmTasks('grunt-contrib-connect');
  grunt.loadNpmTasks('grunt-throttle');

  grunt.registerTask('default', ['connect', 'throttle', 'watch']);

};
```

In retrospect, this is not the ideal design as it forces grunt-watch or something similar to be part of the workflow. I think I might add a configuration parameter to prevent grunt from exiting (a la grunt-connect's keepalive: true). Or maybe just do it by default.

**Comment by roman01la** [comment]
Aha! Now I see it, thanks! :+1:

**Comment by tjgq** [comment]
I actually got around to implementing the keepalive feature yesterday. Have a look at the latest version. Thanks for your feedback!

**Comment by roman01la** [comment]
That's great! Have you considered to add optional latency parameter? I have a plan on implementing load and rendering performance task based on throttling and latency.

I think a simple timeout would be enough for latency implementation.

**Comment by tjgq** [comment]
Yeah, it should be simple enough to implement. I might look into it this weekend, if I've got the time.

**Comment by roman01la** [comment]
Let me send PR for that. Already tested, works fine for me. There's also smarter implementation using queueing, check [bandwidth-limiter-http-proxy](https://github.com/commenthol/bandwidth-limiter-http-proxy/blob/master/proxy.js)
