### ISSUE TITLE
Error: read ECONNRESET

### ISSUE THREAD

**Issue by roman01la** [tjgq/grunt-throttle#4]
I'm getting following error almost all the time:

```
/project_folder/node_modules/grunt-contrib-compass/node_modules/tmp/lib/tmp.js:261
  throw err;
        ^
Error: read ECONNRESET
    at errnoException (net.js:901:11)
    at TCP.onread (net.js:556:19)
```

Looks like there's something goes wrong when Compass compiles Sass and puts it into tmp folder.

**Comment by tjgq** [comment]
I'm not sure whether the fault lies with grunt-throttle, but can you send me the Gruntfile you're using so I can try to reproduce the problem? Thanks.

**Comment by roman01la** [comment]
Looks like it's not the fault of throttle task, but  a conflict when using it with compass task. Unfortunately I have no more actual Gruntfile. You can make a quick test adding the task to some Yeoman generated project, almost every generator scaffolds application with Sass support.

**Comment by tjgq** [comment]
This should not happen anymore as I'm now handling socket errors (as of v0.2.1). Feel free to reopen if the problem persists.
